# Generated by Django 5.0.4 on 2024-04-18 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Адрес')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Область')),
                ('place_of_birth', models.CharField(blank=True, max_length=200, verbose_name='Место рождения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
